# Generated by Django 3.1.4 on 2020-12-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('Toxin-based', 'Toxin-based'), ('Genetic mutations', 'Genetic mutations'), ('Others', 'Others')], max_length=20)),
                ('animalModel', models.CharField(choices=[('MPTP Mice', 'MPTP Mice'), ('MPTP Monkeys', 'MPTP Monkeys'), ('6-OHDA rat', '6-OHDA rat'), ('Rotenone', 'Rotenone'), ('Paraquat', 'Paraquat'), ('MET/MDMA', 'MET/MDMA'), ('Synuclein', 'Synuclein'), ('LRKK2', 'LRKK2'), ('PINK1', 'PINK1'), ('PARKIN', 'PARKIN'), ('DJ-1', 'DJ-1'), ('ATP13A2', 'ATP13A2'), ('SHH', 'SHH'), ('Nurr1', 'Nurr1'), ('Engrailed1', 'Engrailed1'), ('Pitx3', 'Pitx3'), ('C-Rel-NFKB', 'C-Rel-NFKB'), ('MitoPark', 'MitoPark'), ('Atg7', 'Atg7'), ('VMAT2', 'VMAT2')], max_length=45)),
                ('motorbehavior', models.CharField(max_length=100)),
                ('neuronLoss', models.CharField(max_length=30)),
                ('striatalLoss', models.CharField(max_length=30)),
                ('lewyBody', models.CharField(max_length=30)),
                ('measureDateTime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalsApp.patient')),
            ],
        ),
    ]
